### ISSUE TITLE
Wrong artifact name

### ISSUE THREAD

**Issue by PSNRigner** [BentoBoxWorld/addon-acidisland#2]
https://github.com/BentoBoxWorld/addon-acidisland/commit/96694f27e6388040d091f646c5a71ac09ed46942#diff-600376dffeb79835ede4a0b285078036R8

Any reason the artifactId has been changed ?
When compiling all bentobox plugins on a clean environment, the other ones can't build because this is one is installed at the wrong place in maven cache.

**Comment by tastybento** [comment]
The artifact name is correct. The POMs on the other addons need updating. I’ll do that.

**Comment by tastybento** [comment]
Fixed with recent commits.
